---
title: "A Rough Draft Conversation About MAIHDA"
subtitle: "Multilevel Analysis Of Individual Heterogeneity And Discriminatory Accuracy"
author: "Andy Grogan-Kaylor"
format: 
  pdf:
    toc: true
    number-sections: true
---

# The Basic Idea of Multilevel Modeling

```{r}
#| echo: false

set.seed(3846)

N <- 10 # individuals

N_t <- 3 # time points

id <- rep(seq(1, N), each = N_t)

t <- runif(N * N_t, min = 1, max = 10)

u0 <- id

e <- rnorm(N * N_t, 0, 1)

y <- t + u0 + e

mydata <- data.frame(id, t, y)

mydata$y[1] <- NA # wave missing

mydata$y[11] <- NA # wave missing

```

```{r}
#| echo: false
#| warning: false
#| message: false
#| label: fig-MLM
#| fig-cap: "A Basic Multilevel Model"

library(ggplot2)

mycaption <- paste("Every Group Has Its Own Intercept And Slope",
                   "\n",
                   "Every Group Has Different Observations",
                   "\n",
                   "Groups Have Different Numbers of Observations")

ggplot(mydata,
       aes(x = t,
           y = y, 
           color = factor(id))) +
  geom_point(size = 3) +
  geom_smooth(method="lm",
              se = FALSE) +
  theme_minimal() +
  scale_color_viridis_d(name = "group",
                        option = "turbo") +
  labs(title = "A Basic Multilevel Model",
       subtitle = "Every Group Has Its Own Regression Line", 
       caption = mycaption)

ggsave("multilevel.png")

```

# The Basic Idea Of MAIHDA

# Generating The Strata

# Empty Model

# Full Model
